CELL_SIZE = 64, 64 # in pixels
WALL_COLOR = "#B95FD0"
WALL_WIDTH = 1
MAZE_SIZE: tuple[int, int] = 10, 10
BACKGROUND_COLOR: str = "#FCC4C4"
WINDOW_SIZE = MAZE_SIZE[0] * CELL_SIZE[0], MAZE_SIZE[1] * CELL_SIZE[1]
FPS_LIMIT = 60
